- name: Play 1
  hosts: router
  become: yes
  #become_method: sudo

  tasks:

    - name: set ip forwarding = 1
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: iptables - flush filter
      ansible.builtin.iptables:
        chain: "{{ item }}"
        flush: yes
      with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

    - name: iptables - FILTER policy
      ansible.builtin.iptables:
        chain: "{{ item }}"
        policy: DROP
      with_items: [ 'INPUT', 'FORWARD', 'OUTPUT', ]
      
    - name: iptables - ssh INPUT true
      ansible.builtin.iptables:    
        table: filter
        chain: INPUT
        protocol: tcp
        destination_port: 22
        ctstate: NEW,ESTABLISHED,RELATED
        jump: ACCEPT

    - name: iptables - ssh OUTPUT true
      ansible.builtin.iptables:    
        table: filter
        chain: OUTPUT
        protocol: tcp
        destination_port: 22
        ctstate: NEW,ESTABLISHED,RELATED
        jump: ACCEPT

    - name: iptables - FORWARD
      ansible.builtin.iptables:    
        table: filter
        chain: FORWARD
        jump: ACCEPT

    - name: iptables - NAT 
      ansible.builtin.iptables:    
        table: nat
        chain: POSTROUTING
        ctstate: NEW,ESTABLISHED,RELATED
        jump: MASQUERADE
        